# Generated by Django 5.0.6 on 2024-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
