# Generated by Django 5.0.6 on 2024-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnflowapp', '0002_grade_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
